
name: MorphPlayerShops
version: 2.0.0
main: net.naturva.morphie.mps.MorphPlayerShops
author: Morphie
api-version: 1.13
depend: [Vault]
commands:
  ms:
    description: Main command for the MorphPlayerShops plugin!
    usage: /<command>
    aliases: [mshops, ps, pshops]